- hosts: all
  connection: local
  vars:
    DEPLOYMENT_SUFFIX: ""
    DEPLOYMENT_STATE: present
    DEPLOYMENT_UNIT: "full-deployment"
    ingress_domains: []
    deployment_names: []
  vars_files:
    - app_latest_versions.yml
  tasks:
    - name: Debug Infos
      debug:
        msg:
          - "DEPLOYMENT_UNIT: {{ DEPLOYMENT_UNIT }}"
          - "DEPLOYMENT_STATE: {{ DEPLOYMENT_STATE }}"
          - "DEPLOYMENT_VERSION: {{ DEPLOYMENT_VERSION | default('not-set') }}"
          - "DEPLOYMENT_SUFFIX: {{ DEPLOYMENT_SUFFIX }}"
          - "Release namespace: {{ ansible_host }}"

    - include_tasks: playbook-helper/helm_deployment.yaml
