- hosts: all
  connection: local
  vars:
    DEPLOYMENT_SUFFIX: ""
    DEPLOYMENT_STATE: present
    DEPLOYMENT_UNIT: "full-deployment"
    ingress_domains: []
    deployment_names: []
  vars_files:
    - app_latest_versions.yml
  tasks:
    - include_tasks: playbook-helper/helm_deployment.yaml