helm_unifi-controller:
  repo: "k8s-at-home"
  chart: unifi
  version: "4.10.0"
  state: present
  values_helm:
    # service:
    #   main:
    #     enabled: true
    #     type: LoadBalancer
    #     annotations:
    #       metallb.universe.tf/allow-shared-ip: 'true'
    #     loadBalancerIP: 10.1.5.91
    #     ports:
    #       http:
    #         enabled: true
    #         port: 8443
    #         protocol: TCP
    #       controller:
    #         enabled: true
    #         port: 8080
    #         protocol: TCP
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: 500M
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: unifi{{ cluster_domain }}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: unifi-controller-test
                  port: 8443
        tls:
          - hosts:
              - unifi{{ cluster_domain }}
            secretName: unifi-prod-tls
    persistence:
      data:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 15Gi