helm_unifi-controller:
  repo: "k8s-at-home"
  chart: unifi
  version: "5.1.2"
  state: present
  values_helm:
    persistence:
      data:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi