helm_unifi-controller:
  repo: "k8s-at-home"
  chart: unifi
  version: "5.1.2"
  state: present
  values_helm:
    # service with type LoadBalancer can be result in errors
    # for that deploy first wit type: ClusterIP
    service:
      main:
        type: LoadBalancer
    persistence:
      data:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi