---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/dexterposh/podinfo

