---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: "~0.13.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
  interval: 12h0m0s
  values:
    service:
      loadBalancerIP: "10.1.5.90"
      annotations:
        metallb.universe.tf/address-pool: network-services
        metallb.universe.tf/allow-shared-ip: infra-svc
